language: node_js
node_js:
  - 6
# safelist
# branches:
#   only:
#   - master
env:
  global:
  - secure: "NELY80Wt3t+gR1eiDJSjsBiRqhVpy4/NeR8OT669UC7+7yfkftIVKLgl7qVYq26mN3aP7oQoupdwbIgMxcLbijHrBTfYnltK9OQ+S2rGJ6mAmMs131vGQc8QfxfbGQSwS38lKjV/UrvLz++G3NBPrKFbpRzMzTEzty6s4D6RBSjLAcSzqqJJdajIv3SbVlUZ4ZBhLpWOQ5qQkLp7E4FNmcK+5NDSriAXvlzpzRhPXj4XnrRPyc0CugulsxSeLaz8amgL8vUr+Fkb2n4nfZbOKgRWEXwZU8a1kIbkrRZfZrVQ5FMOQCNUWyNLAWjVIzb3dmgo7BkfvMk2esgJGcmebRNP4pLQIppOl2jfNzKu+fXrQEL95LifHlA4zrLtXmOUXb0N9RzPOWOHPdL42iBX5R3I7cJTB8CEK6PP4n32idmFmUSVpyz4tZ5XIPjj9lzieAXYhHHJlcuscPZL0u2Vyh7i2GvPAeVqM2nI5K1pn1fJGWrhamZrrKeqDEn+xREBMoj75x/NNVgaPL3b8TUspnNjbtgIqPrpT0f1gTb1NR4Z3Q0z3hn7hRJba9aV5fPQKbQY7eUv5OE2CnaHAD8XOYnuTvMjc409WL0yEFLwfKGHZm2YVthwl6+A4KaDJu4I4gGfyNzpzcjXbe7XP32mo+tHRhpErRiab3yAnuf+vBk="
  - secure: "WO2RpaL7U6MA3jCeshOduMves2KKEhapjTf5dZjY74qZ8f1LT28Hxp50Mcj3kiwprZ98Y+fjkqliM4M/WlfxRVyqAvSSTJTsRSEgoVizAdgzKIgN35Niems6QTOt1uQUy5aYpFXCzJZy8WXR6k9pHRcjG6ZukpDqBVMaB128utjqK+CL4bHR+pcSoTTitQiERm/LExusIPo0Bw4YHq1sS/OvaMLKkoOoBseXoD67Hn+PmB47jNEDpLjFhS+lMVNjH9NYE+FefYsGVq65UT7DCA5usMZi4vJkvmhJW7//9nBsX0KtA9RmHt0h5SZYMgQbhqYJBed7c01NyByZkHk4lkYZNXIYmH74+QEwP1mDL+erBt+ZQ1Lvxo4E//FDUIdHvIB/sQedg4RBUGUrH4DSkPbGAcNAKGv4ssWvbLZblzIaunBcQuTVG/rWCHVRRaO2E7EbnWwXe7hZCtX4ofZFz3v5603v4a4+tkE+qXGZErHrpwpTSnbHO5HZ8unVvFu9a/h0BMGk2ikcxb8gcF0c/0ipy73zndcpgexpY6XT7PezS9DP3b/PCajiKjWm6B1SHkiY4W9ASNUwXxGIUTvyclgjcKzAtWO0kwiVKWLH7xvvbFUMsfr5i2P/B5XFNY0f4vHvFsSPIlQzpX0rNzqKu9esKfBjX/zAjgHe6teifRA="
  - secure: "hcB2rCnPIk9VLhjDPsTcMQ3dYq469I5g/zVQ1n7fHVD3AgGiT9fIcJvDMeYZ6L3CC9Y0y/c1nDvVV9oBTsjxd3aCUCb53u+N0UIulaQ+ZcmO7YZG3kUwmtiSKCkQSiAkGFMUo8WmoJ2TUnrK2ctvLvmhW+Ke44Zu1loVO6+LsrhrBjtmuEmNhoL1m1G9HzapPGDNkW9dCRDp1nPfw2jrUYvOQPEio1mOVy/yFI0QOX1+1R4eo4IqcdAeGUqq3ULgPELCURzWiwd8/x9SMuuQpc9SNpCAgANJKGUqkcQmW3W/kwB+CvCDwDE6n1CEhDmH4vR/FoPQjGTR43oUzjGiMuJ8BCP7AWdFUmsENkWEfefYC8oTu9O2PtNY5kuhPD/A4dFjWoPnpsN9eryg4CsE//HuIyNBbKD0Y7/GTbJ0RSP+Ktm/BTzd8uUDLrIOfLx3I015f+cwUfZpw7Hywno0QP7z960hqfggNLlV7/xiGFG+g+34tKaRD45r7cqtIb/3fH90FcFgEY9c7iciQshjZdwWh6GM/p5YA0qPXHhnmTKaIwFtEqjyDayrItRCSMSFqUmLRK8wOz9wwcNJIXEIywqRqkkitnO/opU0QHVtIMnrdvBJCmfjxfPrfVQPvvdh1a5/wOzqw04e/nJ9RiZMflBx1sA1IRWg/Mn1xVD7Ggc="
before_install:
  - sudo apt-get install lftp
  - cd logo_creator
install:
  - npm install
#  - npm install -g bower
#  - bower install
script:
  - npm run build
after_success:
  - ./deploy.sh
